Feature/retrieve names
pfbarranco/student-evaluator pull request #6
Opened 2022-08-21 18:47 UTC by pfbarranco

2022-08-21 19:58 UTC, carlosjfcasero requested changes

2022-08-21 19:58 UTC, carlosjfcasero commented on test/app.test.js
> +const fetchMock = require('fetch-mock');
Please, update changelog

2022-08-22 11:26 UTC, pfbarranco commented on test/app.test.js
> +const fetchMock = require('fetch-mock');
Done

2022-08-22 11:27 UTC, carlosjfcasero approved these changes

2022-08-22 11:28 UTC, merged